name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0
          submodules: recursive

      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - run: cargo clippy
